basic_words_meanings = {
    "I": "The subjective pronoun, referring to oneself.",
    "You": "The objective pronoun, referring to the person or persons being spoken to.",
    "He": "Pronoun used for a male person or animal mentioned.",
    "She": "Pronoun used for a female person or animal mentioned.",
    "It": "The pronoun used to refer to a thing previously mentioned.",
    "We": "Refers to oneself and at least one other person.",
    "They": "Pronoun used for people or things previously mentioned.",
    "Be": "Exist or occur; take place.",
    "Have": "To possess, own, or hold.",
    "Do": "To perform an action.",
    "Say": "To utter words to convey information.",
    "Get": "To come to have or hold something.",
    "Make": "To form or create.",
    "Go": "To move from one place to another.",
    "See": "To perceive with the eyes.",
    "Come": "To move toward or into a place near the speaker.",
    "Take": "To lay hold of something with one’s hands.",
    "Think": "To have an opinion, belief, or idea.",
    "Look": "To direct one's gaze.",
    "Want": "To have a desire for something.",
    "Give": "To freely transfer possession.",
    "Use": "To employ for a purpose.",
    "Find": "To discover by chance.",
    "Tell": "To communicate information.",
    "Ask": "To request an answer or information.",
    "Work": "Activity done to achieve a goal.",
    "Seem": "To give an impression.",
    "Feel": "To experience an emotion.",
    "Try": "To make an attempt.",
    "Leave": "To go away from.",
    "Call": "To give a specified name.",
    "May": "Expressing possibility.",
    "Mean": "To signify or intend.",
    "Keep": "To retain possession.",
    "Should": "Indicates obligation or correctness.",
    "Let": "To allow.",
    "Help": "To assist.",
    "Talk": "To converse.",
    "Turn": "To move in a circular direction.",
    "Start": "To begin something.",
    "Might": "Expressing possibility.",
    "Show": "To make visible.",
    "Hear": "To perceive with the ear.",
    "Play": "To engage in enjoyment or recreation.",
    "Run": "To move fast by foot.",
    "Move": "To change position.",
    "Like": "To find enjoyable.",
    "Live": "To remain alive.",
    "Believe": "To accept as true.",
    "Hold": "To grasp with hands.",
    "Bring": "To take to a place.",
    "Happen": "To occur.",
    "Write": "To mark symbols on a surface.",
    "Provide": "To supply or make available.",
    "Sit": "To rest on one’s buttocks.",
    "Jump": "To propel oneself upward.",
    "Dance": "To move rhythmically to music.",
    "Sing": "To make musical sounds with the voice.",
    "Read": "To comprehend written matter.",
    "Draw": "To produce a picture by making marks.",
    "Paint": "To apply liquid color to a surface.",
    "Study": "To devote time to gaining knowledge.",
    "Learn": "To acquire knowledge or skill.",
    "Teach": "To impart knowledge.",
    "Understand": "To interpret meaning.",
    "Remember": "To bring to mind an awareness.",
    "Forget": "To neglect mention or attention.",
    "Meet": "To come into presence of.",
    "Part": "To divide into shares.",
    "Listen": "To give attention to sound.",
    "Speak": "To converse.",
    "Answer": "To react in speech or writing.",
    "Smile": "To form a pleased expression.",
    "Laugh": "To make sounds from amusement.",
    "Cry": "To shed tears as expression of distress.",
    "Sleep": "To rest with eyes closed.",
    "Eat": "To consume food.",
    "Drink": "To consume liquid.",
    "Walk": "To move by lifting and setting down feet.",
    "Stand": "To maintain upright position.",
    "Know": "To be aware by information.",
    "Love": "To feel deep affection.",
    "Hate": "To feel intense dislike.",
    "Dislike": "To feel distaste or aversion.",
    "Enjoy": "To take pleasure in.",
    "Fear": "To be afraid.",
    "Doubt": "To feel uncertain.",
    "Hope": "To expect positively.",
    "Dream": "Series of thoughts during sleep.",
    "Wish": "To express desire.",
    "Care": "To feel concern or interest.",
    "Hurt": "To cause pain.",
    "Heal": "To become sound or healthy.",
}

def get_meaning():
    word = input("Enter a word: ").strip().capitalize()
    meaning = basic_words_meanings.get(word)
    if meaning:
        print(f"{word}: {meaning}")
    else:
        print("Sorry, that word is not in the basic dictionary.")
