basic_words_meanings = {
    "Accept": "To receive willingly.",
    "Account": "A record or statement of financial transactions.",
    "Able": "Having the skill or power to do something.",
    "Acid": "A chemical substance that tastes sour.",
    "Act": "To do something; perform.",
    "Add": "To include or join with something else.",
    "Admit": "To confess or acknowledge.",
    "Age": "Length of time someone has lived.",
    "Agree": "To share an opinion.",
    "Ahead": "In front; forward.",
    "Aid": "Help; support.",
    "Aim": "To direct or point.",
    "Alarm": "A warning sound.",
    "Allergy": "A reaction to certain substances.",
    "Allow": "To permit.",
    "Alone": "Without anyone else.",
    "Alter": "To change.",
    "Amazing": "Causing wonder.",
    "Amount": "The total number or sum.",
    "Amuse": "To entertain.",
    "Analysis": "Detailed examination.",
    "Angel": "A spiritual being.",
    "Angle": "A figure formed by two lines meeting.",
    "Angry": "Feeling or showing displeasure.",
    "Animal": "A living creature except humans.",
    "Annoy": "To bother or irritate.",
    "Annual": "Every year.",
    "Answer": "A reply.",
    "Ant": "A small insect.",
    "Anxiety": "Worry or nervousness.",
    "Apart": "Separated.",
    "Appear": "To come into view.",
    "Apple": "A round fruit.",
    "Apply": "To put into use.",
    "Area": "A region or space.",
    "Argue": "To disagree or dispute.",
    "Arm": "Upper limb of the body.",
    "Army": "A large group of fighters.",
    "Arrive": "To reach a place.",
    "Arrow": "A symbol or weapon.",
    "Article": "A written piece.",
    "Artist": "A person who creates art.",
    "Ask": "To seek information.",
    "Aspect": "A feature; part.",
    "Assume": "To suppose as true.",
    "Attempt": "To try.",
    "Attend": "To be present.",
    "Attention": "Notice taken of something.",
    "Attract": "To draw interest.",
    "Author": "A writer of books or other works.",
    "Auto": "A car.",
    "Available": "Ready for use.",
    "Average": "The typical value.",
    "Avoid": "To stay away.",
    "Award": "A prize or recognition.",
    "Awkward": "Not graceful.",
    "Baby": "A very young child.",
    "Back": "The rear part.",
    "Balance": "Evenness or stability.",
    "Ball": "A round object.",
    "Ban": "To prohibit.",
    "Band": "A musical group.",
    "Bank": "Financial institution.",
    "Base": "Foundation.",
    "Basic": "Fundamental.",
    "Battle": "Fight;",
    "Beach": "Sandy shore.",
    "Bear": "A large animal.",
    "Beat": "Hit or strike.",
    "Beautiful": "Pleasing to the senses.",
    "Because": "Reason for something.",
    "Become": "To begin to be.",
    "Bed": "Furniture to sleep on.",
    "Bee": "Insect that makes honey.",
    "Begin": "To start.",
    "Behavior": "The way one acts.",
    "Behind": "At the back.",
    "Believe": "To accept as true.",
    "Bell": "A ringing object.",
    "Belong": "To be owned.",
    "Below": "Underneath.",
    "Bend": "To curve.",
    "Benefit": "An advantage.",
    "Beside": "Next to.",
    "Best": "Most excellent.",
    "Better": "Improved; greater.",
    "Between": "In the middle.",
    "Beyond": "Further than.",
    "Bicycle": "Two-wheeled vehicle.",
    "Big": "Large in size.",
    "Bird": "Animal with feathers.",
    "Birth": "Coming into life.",
    "Bite": "To use teeth.",
    "Black": "Color of coal.",
    "Blade": "Flat cutting part.",
    "Blank": "Empty space.",
    "Block": "Solid piece.",
    "Blood": "Red body fluid.",
    "Blow": "To send air.",
    "Blue": "Color of the sky.",
    "Board": "Flat surface.",
    "Body": "Physical structure.",
    "Bone": "Hard body part.",
    "Book": "Printed or written work.",
    "Boot": "Shoe covering the ankle.",
    "Border": "Edge or boundary.",
    "Born": "Brought into life.",
    "Borrow": "Take to return later.",
    "Boss": "Person in charge.",
    "Both": "Two together.",
    "Bottle": "Container for liquids.",
    "Bottom": "Lowest part.",
    "Bow": "To bend or a tied ribbon.",
    "Box": "A container.",
    "Boy": "Male child.",
    "Brain": "Thinking organ.",
    "Branch": "Part of a tree.",
    "Brave": "Not afraid.",
    "Bread": "Food made from flour.",
    "Break": "To separate.",
    "Breakfast": "Morning meal.",
    "Breath": "Air taken in.",
    "Breathe": "To take air in and out.",
    "Brick": "Building block.",
    "Bridge": "Structure over water.",
    "Brief": "Short in time.",
    "Bright": "Giving off lots of light.",
    "Bring": "To carry to someone.",
    "Broad": "Wide; large.",
    "Brother": "Male sibling.",
    "Brown": "Earth color.",
    "Brush": "Object for cleaning or painting.",
    "Build": "To make or construct.",
    "Bunch": "A group of things.",
    "Burn": "Consume by fire.",
    "Burst": "Break suddenly.",
    "Bus": "Large vehicle.",
    "Business": "Trade or activity for money.",
    "Busy": "Occupied.",
    "But": "Except; however.",
    "Buy": "To pay for something.",
    "By": "Next to or through.",
    "Cable": "Thick wire.",
    "Cake": "Sweet baked dessert.",
    "Call": "To name or phone.",
    "Calm": "Peaceful.",
    "Camera": "Takes photos.",
    "Camp": "Temporary shelter.",
    "Can": "Able to.",
    "Cancel": "To call off.",
    "Cancer": "Serious disease.",
    "Candy": "Sweet treat.",
    "Cap": "Hat.",
    "Capital": "Main city; money.",
    "Captain": "Leader.",
    "Car": "Automobile.",
    "Card": "Small flat piece for communication.",
    "Care": "Serious attention.",
    "Career": "Job or profession.",
    "Careful": "Cautious.",
    "Carry": "To hold and move.",
    "Case": "Container; example.",
    "Cash": "Coins and bills.",
    "Cat": "Domesticated animal.",
    "Catch": "To capture.",
    "Ceiling": "Top inner surface.",
    "Cell": "Small room; basic unit.",
    "Center": "Middle point.",
    "Central": "In the center.",
    "Century": "One hundred years.",
    "Certain": "Sure.",
    "Chain": "Series of linked rings.",
    "Chair": "Seat with back.",
    "Chance": "Possibility.",
    "Change": "To make different.",
    "Channel": "Path or TV station.",
    "Charge": "Price or attack.",
    "Chart": "Visual data.",
    "Cheap": "Low cost.",
    "Check": "To examine.",
    "Cheese": "Food from milk.",
    "Chemical": "Substance used or made by chemistry.",
    "Chest": "Upper body part or box.",
    "Chicken": "Common farm bird.",
    "Chief": "Leader.",
    "Child": "Young person.",
    "Choice": "Option to select.",
    "Choose": "To pick.",
    "Church": "Religious building.",
    "Circle": "Round shape.",
    "City": "Large town.",
    "Claim": "To say something is yours.",
    "Class": "Category or group.",
    "Clean": "Not dirty.",
    "Clear": "Easy to see through.",
    "Climb": "Go up.",
    "Clock": "Shows time.",
    "Close": "Shut or near.",
    "Cloth": "Fabric.",
    "Cloud": "Water vapor in the air.",
    "Club": "Group or stick.",
    "Coach": "Trainer or vehicle.",
    "Coal": "Black mineral.",
    "Coast": "Land by sea.",
    "Coat": "Outer garment.",
    "Code": "Secret system or symbols.",
    "Cold": "Low temperature.",
    "Collar": "Neck part of clothing.",
    "Collect": "To gather things.",
    "Color": "Visual hue.",
    "Column": "Vertical line.",
    "Come": "Approach.",
    "Comfort": "Physical or mental ease.",
    "Common": "Shared by many.",
    "Company": "Business or companionship.",
    "Compare": "Find likenesses and differences.",
    "Compass": "Tool for direction.",
    "Complete": "Finish fully.",
    "Completely": "Fully done.",
    "Complex": "Not simple.",
    "Computer": "Electronic device.",
    "Condition": "State of something.",
    "Connect": "Join together.",
    "Consider": "Think carefully.",
    "Consist": "Made up of.",
    "Constant": "Always happening.",
    "Construct": "Build.",
    "Contact": "Touch or communication.",
    "Contain": "To hold inside.",
    "Continue": "Keep going.",
    "Control": "Command or manage.",
    "Cook": "Prepare food.",
    "Cool": "Slightly cold.",
    "Copy": "Make a duplicate.",
    "Corner": "Where two lines meet.",
    "Correct": "Right or true.",
    "I": "The subjective pronoun, referring to oneself.",
    "You": "The objective pronoun, referring to the person or persons being spoken to.",
    "He": "Pronoun used for a male person or animal mentioned.",
    "She": "Pronoun used for a female person or animal mentioned.",
    "It": "The pronoun used to refer to a thing previously mentioned.",
    "We": "Refers to oneself and at least one other person.",
    "They": "Pronoun used for people or things previously mentioned.",
    "Be": "Exist or occur; take place.",
    "Have": "To possess, own, or hold.",
    "Do": "To perform an action.",
    "Say": "To utter words to convey information.",
    "Get": "To come to have or hold something.",
    "Make": "To form or create.",
    "Go": "To move from one place to another.",
    "See": "To perceive with the eyes.",
    "Come": "To move toward or into a place near the speaker.",
    "Take": "To lay hold of something with one’s hands.",
    "Think": "To have an opinion, belief, or idea.",
    "Look": "To direct one's gaze.",
    "Want": "To have a desire for something.",
    "Give": "To freely transfer possession.",
    "Use": "To employ for a purpose.",
    "Find": "To discover by chance.",
    "Tell": "To communicate information.",
    "Ask": "To request an answer or information.",
    "Work": "Activity done to achieve a goal.",
    "Seem": "To give an impression.",
    "Feel": "To experience an emotion.",
    "Try": "To make an attempt.",
    "Leave": "To go away from.",
    "Call": "To give a specified name.",
    "May": "Expressing possibility.",
    "Mean": "To signify or intend.",
    "Keep": "To retain possession.",
    "Should": "Indicates obligation or correctness.",
    "Let": "To allow.",
    "Help": "To assist.",
    "Talk": "To converse.",
    "Turn": "To move in a circular direction.",
    "Start": "To begin something.",
    "Might": "Expressing possibility.",
    "Show": "To make visible.",
    "Hear": "To perceive with the ear.",
    "Play": "To engage in enjoyment or recreation.",
    "Run": "To move fast by foot.",
    "Move": "To change position.",
    "Like": "To find enjoyable.",
    "Live": "To remain alive.",
    "Believe": "To accept as true.",
    "Hold": "To grasp with hands.",
    "Bring": "To take to a place.",
    "Happen": "To occur.",
    "Write": "To mark symbols on a surface.",
    "Provide": "To supply or make available.",
    "Sit": "To rest on one’s buttocks.",
    "Jump": "To propel oneself upward.",
    "Dance": "To move rhythmically to music.",
    "Sing": "To make musical sounds with the voice.",
    "Read": "To comprehend written matter.",
    "Draw": "To produce a picture by making marks.",
    "Paint": "To apply liquid color to a surface.",
    "Study": "To devote time to gaining knowledge.",
    "Learn": "To acquire knowledge or skill.",
    "Teach": "To impart knowledge.",
    "Understand": "To interpret meaning.",
    "Remember": "To bring to mind an awareness.",
    "Forget": "To neglect mention or attention.",
    "Meet": "To come into presence of.",
    "Part": "To divide into shares.",
    "Listen": "To give attention to sound.",
    "Speak": "To converse.",
    "Answer": "To react in speech or writing.",
    "Smile": "To form a pleased expression.",
    "Laugh": "To make sounds from amusement.",
    "Cry": "To shed tears as expression of distress.",
    "Sleep": "To rest with eyes closed.",
    "Eat": "To consume food.",
    "Drink": "To consume liquid.",
    "Walk": "To move by lifting and setting down feet.",
    "Stand": "To maintain upright position.",
    "Know": "To be aware by information.",
    "Love": "To feel deep affection.",
    "Hate": "To feel intense dislike.",
    "Dislike": "To feel distaste or aversion.",
    "Enjoy": "To take pleasure in.",
    "Fear": "To be afraid.",
    "Doubt": "To feel uncertain.",
    "Hope": "To expect positively.",
    "Dream": "Series of thoughts during sleep.",
    "Wish": "To express desire.",
    "Care": "To feel concern or interest.",
    "Hurt": "To cause pain.",
    "Heal": "To become sound or healthy.",
    "Above": "At a higher level or position.",
    "Across": "From one side to the other.",
    "Act": "To do something; to take action.",
    "Add": "To put something together with something else.",
    "Against": "In opposition to.",
    "Ago": "Before now; in the past.",
    "Air": "The invisible gas around the earth.",
    "All": "Every one; the whole amount.",
    "Also": "In addition.",
    "Among": "In the middle of.",
    "And": "Used to connect words or phrases.",
    "Animal": "A living creature not a human or plant.",
    "Answer": "A reply to a question.",
    "Any": "One or some, no matter which.",
    "App": "Short for application; computer program.",
    "Apple": "A round fruit with red or green skin.",
    "Area": "A region or space.",
    "Arm": "The upper limb of the body.",
    "Art": "Creation of beauty through skill.",
    "Ask": "To request information.",
    "Atom": "The smallest unit of matter.",
    "Aunt": "The sister of one’s parent.",
    "Baby": "A very young child.",
    "Back": "The rear part of something.",
    "Bad": "Not good; undesirable.",
    "Bag": "A container for carrying things.",
    "Ball": "A round object used in games.",
    "Band": "A group of musicians.",
    "Bank": "A place to keep money.",
    "Bar": "A long rod or place where drinks are sold.",
    "Base": "The bottom support; foundation.",
    "Bat": "A flying mammal or a club used in sports.",
    "Bay": "A body of water partly enclosed by land.",
    "Bed": "A piece of furniture to sleep on.",
    "Bee": "An insect that makes honey.",
    "Bell": "A hollow instrument that rings when struck.",
    "Bend": "To curve something.",
    "Bet": "To risk money on a result.",
    "Big": "Of large size.",
    "Bird": "A feathered animal that can usually fly.",
    "Bit": "A small piece.",
    "Black": "A color without brightness.",
    "Block": "A solid piece, often rectangular.",
    "Blood": "The red liquid in the body.",
    "Blow": "A strong push of air.",
    "Blue": "The color of the sky.",
    "Board": "A flat piece of wood or other material.",
    "Boat": "A small vessel for traveling on water.",
    "Body": "The physical part of a person or animal.",
    "Bone": "The hard part inside the body.",
    "Book": "A set of written pages.",
    "Boot": "A type of shoe that covers the ankle.",
    "Born": "Brought into life.",
    "Boss": "The person in charge.",
    "Both": "Refers to two things together.",
    "Bottle": "A container, usually for liquid.",
    "Box": "A container with flat sides.",
    "Boy": "A male child.",
    "Brain": "The organ inside the head for thinking.",
    "Branch": "A part of a tree that grows out from the trunk.",
    "Brass": "A yellow metal.",
    "Bread": "Food made from flour and water.",
    "Break": "To separate into pieces.",
    "Bridge": "A structure for going over obstacles.",
    "Bring": "To take something or someone to another place.",
    "Broad": "Wide; large from side to side.",
    "Brother": "A boy or man who has the same parents as another.",
    "Brown": "Color like chocolate.",
    "Brush": "An object with bristles for cleaning or painting.",
    "Bug": "An insect.",
    "Build": "To make by putting parts together.",
    "Burn": "To consume by fire.",
    "Bus": "A large vehicle for many passengers.",
    "Business": "Activity of buying and selling.",
    "Busy": "Having a lot to do.",
    "But": "However; except.",
    "Buy": "To obtain by paying money.",
    "By": "Near to or next to something.",
    "Cabin": "A small wood house.",
    "Cable": "A thick rope or wire.",
    "Cake": "A sweet baked food.",
    "Call": "To shout or phone.",
    "Camera": "A device for taking photos.",
    "Camp": "Temporary shelter, usually outdoors.",
    "Can": "To be able to; a container.",
    "Cancel": "To stop something that was planned.",
    "Cancer": "A serious disease with uncontrolled cell growth.",
    "Candle": "Wax cylinder for light.",
    "Candy": "Sweet food made from sugar.",
    "Capital": "The city or town representing government.",
    "Car": "A road vehicle with an engine.",
    "Card": "A small, flat object for identification or greeting.",
    "Care": "Serious attention or concern.",
    "Carry": "To hold and move something.",
    "Case": "A container or an instance of something.",
    "Cash": "Money in notes or coins.",
    "Cat": "A small, domestic animal kept as a pet.",
    "Catch": "To capture or seize.",
    "Cause": "The reason something happens.",
    "Cell": "The basic unit of living things.",
    "Center": "The middle point.",
    "Central": "Of the center; main.",
    "Century": "100 years.",
    "Certain": "Sure; definite.",
    "Chair": "A seat with a back for one person.",
    "Chance": "A possibility.",
    "Change": "To make or become different.",
    "Channel": "A path for water or TV broadcast.",
    "Charge": "To ask for payment or attack.",
    "Chart": "A sheet with information arranged in a table or diagram.",
    "Check": "To examine something.",
    "Cheese": "A food made from milk.",
    "Chicken": "A common farm bird.",
    "Chief": "The leader or most important part.",
    "Child": "A young person.",
    "Choice": "An act of choosing.",
    "Choose": "To pick from options.",
    "Church": "A building for Christian worship.",
    "Circle": "A round shape with every point the same distance from the center.",
    "City": "A large town.",
    "Claim": "To say something belongs to you or is true.",
    "Class": "A group of students or a category of things.",
    "Clean": "Not dirty.",
    "Clear": "Easy to understand; transparent.",
    "Clock": "A device measuring time.",
    "Close": "To shut; near.",
    "Cloth": "A material for making clothes.",
    "Cloud": "A mass of vapor in the sky.",
    "Club": "An organization or a stick for hitting.",
    "Coach": "A trainer or a large vehicle.",
    "Coast": "The land near the sea.",
    "Coat": "A piece of clothing worn over other clothes.",
    "Coffee": "A drink made from roasted seeds.",
    "Cold": "Low temperature.",
    "Color": "Visual appearance; hue.",
    "Come": "To move toward the speaker.",
    "Comfort": "A state of physical or mental ease.",
    "Common": "Not rare; shared by many.",
    "Company": "A business or group of people together.",
    "Compare": "To look for similarities and differences.",
    "Computer": "An electronic machine for data processing.",
    "Concern": "Worry or care about something.",
    "Condition": "The state of something.",
    "Conference": "A formal meeting for discussion.",
    "Congress": "A group of representatives who make laws.",
    "Connect": "To join together.",
    "Consider": "To think about carefully.",
    "Consist": "To be made up of.",
    "Control": "The power to make decisions.",
    "Cook": "A person who prepares food.",
    "Cool": "Slightly cold or fashionable.",
    "Cop": "Slang for police officer.",
    "Copy": "To make a duplicate.",
    "Core": "The central part.",
    "Corner": "The point where two lines meet.",
    "Cost": "The price to be paid.",
    "Could": "Was/were able to.",
    "Count": "To find the total number.",
    "Country": "A nation.",
    "County": "A region within a country.",
    "Couple": "Two people or things together.",
    "Course": "A direction or a class.",
    "Court": "A place for playing sports or holding trials.",
    "Cover": "To place something over or hide.",
    "Create": "To make something new.",
    "Crew": "A group of people working together.",
    "Crime": "An illegal act.",
    "Cross": "To go from one side to another.",
    "Crowd": "A large group of people.",
    "Cry": "To shed tears or make a loud noise.",
    "Cultural": "Related to culture or society.",
    "Cup": "A small bowl for drinking.",
    "Current": "Happening now or a flow of electricity/water.",
    "Cut": "To divide with a blade.",
    "Dark": "With little or no light.",
    "Data": "Information, usually numbers or facts.",
    "Day": "A period of 24 hours or the time when it is light.",
    "Deal": "An agreement or arrangement.",
    "Death": "The end of life.",
    "Debate": "A formal discussion.",
    "Debt": "Money owed.",
    "Decide": "To make a choice.",
    "Declare": "To state openly.",
    "Deep": "Extending far down or in.",
    "Word": "A single unit of language with meaning.",
    "Time": "The measurement or passage of moments.",
    "Number": "A symbol showing quantity or order.",
    "Way": "A method or manner of doing something.",
    "People": "Human beings, group or individuals.",
    "Water": "A clear liquid needed for life.",
    "Day": "A 24-hour period.",
    "Part": "A piece or section of a whole.",
    "Sound": "What is heard by ears.",
    "Work": "Activity or effort to achieve a result.",
    "Place": "A particular location.",
    "Year": "Twelve months.",
    "Back": "The rear side of something.",
    "Thing": "An object or item.",
    "Name": "A word used to identify someone or something.",
    "Sentence": "A group of words expressing a complete thought.",
    "Man": "An adult male human.",
    "Line": "A long, narrow mark or row.",
    "Boy": "A male child.",
    "Farm": "Land for growing crops or raising animals.",
    "End": "The last part of something.",
    "Men": "Male persons.",
    "Land": "Solid part of the Earth's surface.",
    "Home": "A place where someone lives.",
    "Hand": "The part of the body at the end of the arm.",
    "Picture": "A drawing or photograph.",
    "Animal": "A living creature not a plant.",
    "House": "A building to live in.",
    "Page": "One side of a sheet of paper.",
    "Letter": "A written symbol or message.",
    "Point": "A small spot, or an exact location.",
    "Mother": "A female parent.",
    "Answer": "A reply to a question.",
    "America": "A country in North America.",
    "World": "The planet and its people.",
    "Food": "Anything that can be eaten.",
    "Country": "A nation with its own government.",
    "Plant": "A living thing that grows in soil.",
    "School": "A place for education.",
    "Father": "A male parent.",
    "Tree": "A tall plant with a trunk and branches.",
    "City": "A large town.",
    "Earth": "The planet we live on.",
    "Eye": "The organ for sight.",
    "Head": "The top part of the body.",
    "Story": "A tale or account of events.",
    "Example": "Something used to show or explain.",
    "Life": "The condition of living.",
    "Paper": "Material for writing or printing.",
    "Group": "A number of people or things together.",
    "Children": "Young people; kids.",
    "Side": "The position or part to the left or right.",
    "Feet": "The parts of the body below the ankles.",
    "Car": "A vehicle with wheels and an engine.",
    "Mile": "A unit of distance (about 1.6 km).",
    "Night": "The time when it's dark; opposite of day.",
    "Sea": "A large area of salty water.",
    "River": "A large, flowing body of water.",
    "State": "A region with government.",
    "Book": "Pages bound together.",
    "Idea": "A thought or concept.",
    "Face": "The front part of the head with eyes, nose, mouth.",
    "Indian": "A person from India.",
    "Girl": "A female child.",
    "Mountain": "A large, natural rise of land.",
    "List": "A series of names or items.",
    "Song": "A musical composition with words.",
    "Family": "Parents and children together.",
    "He": "Pronoun for a male.",
    "A": "An indefinite article used for something not specific.",
    "One": "The number after zero.",
    "All": "Every one.",
    "An": "Like 'a', used for vowel sounds.",
    "Each": "Every single one.",
    "Other": "Different from the one mentioned.",
    "Many": "More than a few.",
    "Some": "An unspecified amount.",
    "Two": "The number after one.",
    "More": "A larger amount.",
    "Long": "Not short; greater distance.",
    "New": "Not old; just made.",
    "Little": "Small in size.",
    "Most": "Greatest amount.",
    "Good": "Suitable; desirable.",
    "Great": "Large; excellent.",
    "Right": "Correct or proper.",
    "Mean": "To have a particular meaning.",
    "Old": "Having lived a long time.",
    "Any": "One or some, no matter which.",
    "Same": "Not different.",
    "Three": "The number after two.",
    "Small": "Not large.",
    "Another": "One more; different one.",
    "Large": "Great in size.",
    "Big": "Of considerable size.",
    "Even": "Level; equal.",
    "Such": "Of this kind.",
    "Different": "Not the same.",
    "Kind": "Type; a helpful nature.",
    "Still": "Not moving.",
    "High": "Tall; far up.",
    "Every": "All members of a group.",
    "Own": "Belonging to oneself.",
    "Light": "Opposite of heavy or dark.",
    "Left": "Opposite of right or departed.",
    "Few": "A small number.",
    "Next": "Immediately following.",
    "Hard": "Solid or difficult.",
    "Both": "Two together.",
    "Important": "Of great significance.",
    "White": "The color of milk.",
    "Four": "The number after three.",
    "Second": "Comes after first.",
    "Enough": "The required amount.",
    "Above": "At a higher level.",
    "Young": "Not old.",
    "Not": "Negates meaning.",
    "When": "At the time that.",
    "There": "In that place.",
    "How": "In what way.",
    "Up": "Positioned higher.",
    "Out": "Away; not inside.",
    "Then": "At that time.",
    "So": "In that way; therefore.",
    "No": "Not any; refusal.",
    "First": "Arriving before others.",
    "Now": "At this moment.",
    "Only": "No others beside.",
    "Very": "To a high degree.",
    "Just": "Exactly; recently.",
    "Where": "At what place.",
    "Much": "A large amount.",
    "Before": "Earlier than.",
    "Too": "Also; excessively.",
    "Also": "In addition.",
    "Around": "On every side.",
    "Well": "In a good way; healthy.",
    "Here": "In this place.",
    "Why": "For what reason.",
    "Again": "Once more.",
    "Off": "Not on; away.",
    "Away": "Not here; distant.",
    "Near": "Close by.",
    "Below": "Under; at a lower level.",
    "Last": "Coming after all others.",
    "Never": "Not ever.",
    "Always": "At all times.",
    "Together": "With each other.",
    "Often": "Many times.",
    "Once": "One time.",
    "Later": "Afterwards.",
    "Far": "Distant.",
    "Really": "In fact.",
    "Almost": "Nearly; not quite.",
    "Sometimes": "Occasionally.",
    "Soon": "Quickly; in a short time.",
    "Of": "Belonging to.",
    "To": "Indicating direction or position.",
    "In": "Inside.",
    "For": "Intended to belong or benefit.",
    "On": "Touching or supported by.",
    "With": "Accompanied by.",
    "At": "In a specific place.",
    "From": "Starting at.",
    "By": "Through, or beside.",
    "About": "Concerning.",
    "Into": "To the inside.",
    "Down": "Lower direction.",
    "Over": "Above and covering.",
    "After": "Following in time.",
    "Through": "In one side and out the other.",
    "Between": "At, or in, the middle of.",
    "Under": "Lower than.",
    "Along": "Following the length.",
    "Until": "Up to a point in time.",
    "Without": "Not having.",
    "You": "Refers to the listener.",
    "That": "Referring to something mentioned.",
    "It": "Neutral pronoun.",
    "He": "Male pronoun.",
    "His": "Possessive male pronoun.",
    "They": "Refers to multiple persons.",
    "I": "Speaker; oneself.",
    "This": "Pointing to nearby object.",
    "What": "Asking for information.",
    "We": "Plural first person.",
    "Your": "Belonging to you.",
    "Which": "Asking about choice.",
    "She": "Female pronoun.",
    "Their": "Belonging to them.",
    "Them": "Refers to multiple.",
    "These": "More than one nearby.",
    "Her": "Belonging to female.",
    "Him": "Belonging to male.",
    "My": "Belonging to me.",
    "Who": "Asking about person.",
    "Its": "Belonging to it.",
    "Me": "Refers to the speaker.",
    "Our": "Belonging to us.",
    "Us": "Refers to speaker and others.",
    "Something": "A thing that is not identified.",
    "Those": "More than one distant object.",
    "And": "Connects words or clauses.",
    "As": "To the same degree.",
    "Or": "Indicates choice.",
    "But": "Contrast with previous.",
    "If": "Condition.",
    "Than": "Indicates comparison.",
    "Because": "Reason for.",
    "While": "During the time.",
    "It's": "It is.",
    "Don't": "Do not."
    }
